// <auto-generated />
using System;
using CrimeManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrimeManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("CrimeManagementSystem.Models.Crime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CrimeDate");

                    b.Property<string>("CrimeLocation")
                        .IsRequired();

                    b.Property<DateTime>("CrimeRegistrationDate");

                    b.Property<string>("CrimeStatus")
                        .IsRequired();

                    b.Property<string>("CrimeType");

                    b.Property<int>("CriminalId");

                    b.Property<string>("Description");

                    b.Property<bool>("HasEvidence");

                    b.Property<int>("OfficerId");

                    b.Property<string>("Priority")
                        .IsRequired();

                    b.Property<int>("VictimId");

                    b.HasKey("Id");

                    b.HasIndex("CriminalId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("VictimId");

                    b.ToTable("Crimes");
                });

            modelBuilder.Entity("CrimeManagementSystem.Models.Criminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<DateTime>("LockinDate");

                    b.Property<DateTime?>("LockoutDate");

                    b.Property<string>("LockupLocation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Criminals");
                });

            modelBuilder.Entity("CrimeManagementSystem.Models.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CasePending");

                    b.Property<int>("CaseSolved");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Designation");

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Phone");

                    b.Property<string>("PostingLocation");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<DateTime?>("RetirementDate");

                    b.HasKey("Id");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("CrimeManagementSystem.Models.Victim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<DateTime?>("DeathDate");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Phone");

                    b.Property<string>("ZipCode")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Victims");
                });

            modelBuilder.Entity("CrimeManagementSystem.Models.Crime", b =>
                {
                    b.HasOne("CrimeManagementSystem.Models.Criminal", "Criminal")
                        .WithMany("Crimes")
                        .HasForeignKey("CriminalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CrimeManagementSystem.Models.Officer", "Officer")
                        .WithMany("Crimes")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CrimeManagementSystem.Models.Victim", "Victim")
                        .WithMany("Crimes")
                        .HasForeignKey("VictimId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
